server:
  port: 9393
spring:
  application:
    name: zuul-ratelimit
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7777/eureka/
#构建路由地址
zuul:
  routes:
    #自定义
    demo2:
      #匹配的路由规则
      path: /demo/**
      #路由的目标服务名
      serviceId: demo
    # 配置限流
    ratelimit:
      enabled: true
      # 对应存储类型(用来统计存储统计信息)
      repository: redis
      # 配置路由的策略
      policy-list:
        demo:
          # 每秒允许多少个请求
          - limit: 2
            # 刷新时间(单位秒)
            refresh-interval: 1
            # 根据什么统计
            type:
              - url
